### ISSUE TITLE
Build fails with both shaded OTP and non-shaded OTP

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#106]
At first analyst-server would not build because it was using two conflicting versions of JTS. OTP depends on geotools 10.5, which depends on JTS 1.13, while gtfs-lib depends on JTS 1.8. PreparedPolygon from JTS 1.13 does not like Polygon from JTS 1.8. 

We were only making one JAR of OTP, the “shaded” one that includes all the dependencies. That was being deployed to the Maven repo. It’s pure luck that this ever worked at all, since the transitive dependencies of OTP can’t be seen/managed by build tools that include OTP via a Maven repo.

This has been fixed via ticket https://github.com/opentripplanner/OpenTripPlanner/issues/1986 .

Now, depending on the non-shaded OTP JAR, we get another error from SBT/Play:
`java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.apache.httpcomponents#httpclient;4.3.1`

All references I can find to this error on the web indicate that it's a bug in Ivy but if so it hasn't been fixed after many years. As a temporary fix, you can add this problematic transitive dependency directly to the SBT build (see http://stackoverflow.com/a/25126544/778449). In this case, I added  `"org.apache.httpcomponents" % "httpclient" % "4.3.1",` and the build completes successfully. Why, I have no idea. Might it have something to do with circular dependencies?

Increasing the logging level to Debug (add `logLevel := Level.Debug` to build.sbt) does not reveal anything particularly helpful.

**Comment by mattwigway** [comment]
Fixed in master as well.
