### ISSUE TITLE
Send only profileRequest, never routingRequest

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#160]
Our code will be simpler if we make AnalystClusterRequest a wrapper around ProfileRequest. Currently it can contain either a ProfileRequest or a RoutingRequest. Non-transit requests do not really need to use profile routing, because travel time does not vary as a function of departure time, but we can handle this by making the window zero-width or just ignoring the end time when no transit modes are specified.

**Comment by abyrd** [comment]
worker and broker updated in OTP branch nontransit-analyst

**Comment by mattwigway** [comment]
Done.
