### ISSUE TITLE
VertexNotFoundException when trying single-point analysis

### ISSUE THREAD

**Issue by markjd84** [conveyal/analyst-server#73]
Have loaded up an OSM pbf file using vanilla-extract, and got GTFS and shapefiles loaded up as well. However when trying to do a single-point analysis I get the following. Is there something wrong with my vexserver or GTFS?

```
[info] o.o.p.AnalystProfileRouterPrototype - access modes: TraverseMode (WALK)
[info] o.o.p.AnalystProfileRouterPrototype - egress modes: TraverseMode (WALK)
[info] o.o.p.AnalystProfileRouterPrototype - direct modes: TraverseMode (WALK)
org.opentripplanner.routing.error.VertexNotFoundException: vertices not found: [from, to]
        at org.opentripplanner.routing.core.RoutingContext.check(RoutingContext.java:321)
        at org.opentripplanner.routing.core.RoutingRequest.setRoutingContext(RoutingRequest.java:799)
        at org.opentripplanner.profile.AnalystProfileRouterPrototype.findClosestStops(AnalystProfileRouterPrototype.java:215)
        at org.opentripplanner.profile.AnalystProfileRouterPrototype.route(AnalystProfileRouterPrototype.java:100)
        at otp.AnalystProfileRequest.createSurfaces(AnalystProfileRequest.java:48)
        at controllers.Api$2.apply(Api.java:163)
        at controllers.Api$2.apply(Api.java:156)
...
```

**Comment by knaaptime** [comment]
after having a previously functional vex/analyst installation (prior to OTP API chages), i am now seeing this problem as well

pbf is a full planet extract

**Comment by markjd84** [comment]
Did you have any luck finding a workaround?

**Comment by knaaptime** [comment]
I'm not seeing this issue anymore

**Comment by markjd84** [comment]
We were getting it all the time when using a MapZen metro extracts PBF of a particular city; using a whole-planet PBF results in fewer problems but there is still some of our GTFS that results in this error (even though it displays fine in the UI and all the georeferencing is ok). 

Part of the problem seems to be that it can't link the stops from some files to the road network when importing, but no idea why that is the case.

**Comment by mattwigway** [comment]
The linker code was rewritten from scratch last month, so I think this is solved. Let me know if you continue to experience problems. Thanks for the report!

**Comment by 3vivekb** [comment]
I hit a few errors that ended with a vertex exception not found.

Many of the stops are "not near any streets; it will not be usable"
Not sure why that is happening.

Here is a log of my worker:
[worker.log.txt](https://github.com/conveyal/analyst-server/files/435944/worker.log.txt)
