### ISSUE TITLE
aggregation without weighting

### ISSUE THREAD

**Issue by knaaptime** [conveyal/analyst-server#82]
when aggregating a regional analysis (as far as I can tell) users are forced to select a weighting attribute. It would be nice to have the ability to aggregate to another geometry without being forced to normalize the aggregation

i.e. compute accessibility on set of points, aggregate to polygons (tracts, counties, etc) and select <none> in the "weighted by shapefile" dropdown

obviously this can be solved on the data side by including a column of ones, but would be good to have the option on the platform side.

**Comment by mattwigway** [comment]
The use case you have given makes sense if the points represent individuals; mostly where we've worked we've had aggregate data and aggregating that up without weighting it is incorrect. I'm somewhat inclined to think of this as a special case where the weights are equal to prevent users from aggregating aggregate data without weights, which is not mathematically sound. That said I see your argument, so I don't have strong feelings.

**Comment by knaaptime** [comment]
this may be related to https://github.com/conveyal/analyst-server/issues/84#issuecomment-102530073

To give a bit more context, I have disaggregate employment data (QCEW) for which I would like to compute accessibility. But I want to display access (origins) using polygons, not points, which requires aggregating to some relatively small geography like census blocks. 

Personally, I'm not a fan of the Bertraud measure because a) I think accessibility makes more sense as a *potential* measure rather than a realized one, and b) normalizing accessibility by the population inside a given census block suggests that somehow accessibility is diminished as population inside the block increases. Conceptually, this only makes sense if you assume people are competing for jobs *only* with the people inside their census block, which certainly isn't true (I suppose you could also make a congestion argument, but that's equally murky). There's no way to identify the source of competition, so there's no good way to identify an denominator 

So, what would be useful is the ability to display the total number of jobs available within a given commute from each census block, without the explicit need to weight by the attributes of that block. But since I have disaggregate employment data, I want the ability to keep that precision in the accessibility calculation

**Comment by mattwigway** [comment]
Ah, I think there's some misunderstanding here, probably created by some confusing comments in the code (and additionally some code that incorrectly applied the algorithm that I replaced in November or December). Accessibility is never normalized in the Bertaud measure, it is weighted (the division is just to divide by the sum of the weights). This is simply a weighted average; we probably shouldn't even call it Bertaud, as his findings were not the methodology of the averaging but its relationship to economic performance, and his findings were only about doing the averaging at a metropolitan scale. If you're not trying to aggregate to larger origins than those for which you originally calculated, there's no need to use Bertaud. But for your use case we do need to implement #84.

**Comment by knaaptime** [comment]
yeah, that makes a lot more sense. thanks for clearing that up

**Comment by mattwigway** [comment]
@knaaptime can we close this issue or is this still something that you'd like to see?
