### ISSUE TITLE
Non-monotonic graphs

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analyst-server#91]
When there are extremely sharp corners in the graph, it can be non-monotonic (probably due to line smoothing). For example, on Vashon:

![screenshot from 2015-04-15 11 30 03](https://cloud.githubusercontent.com/assets/566958/7162472/cb77fe82-e362-11e4-80db-270173591752.png)

**Comment by ansoncfit** [comment]
We've seen the same behavior on the graphs for the Boston network (though
it's less dramatic).  The pointEstimates displayed with the mouseover are
monotonic, so it does seem to be the line smoothing.

Anson Stewart

**Comment by mattwigway** [comment]
This should fix this issue: https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate_tension
